#!/bin/bash

activate() {
	cat $HOME/Codes/no-distract/1.txt >/etc/hosts
	cat $HOME/Codes/no-distract/ban.txt >>/etc/hosts
	cat $HOME/Codes/no-distract/2.txt >>/etc/hosts
}

deactivate() {
	cat $HOME/Codes/no-distract/1.txt >/etc/hosts
	cat $HOME/Codes/no-distract/2.txt >>/etc/hosts
}

if [ $1 == "on" ]; then activate; fi

if [ $1 == "off" ]; then deactivate; fi

if ! test -n $1; then activate; fi

/etc/init.d/nscd restart
